"""State management for GIA Agentic v2 workflow."""

from src.state.enums import (
    ResearchStatus,
    CritiqueSeverity,
    EvidenceStrength,
    PaperType,
    ResearchType,
    GapType,
    GapSignificance,
    # Sprint 6 enums
    SectionType,
    WritingStatus,
    StyleViolationType,
    CitationStyle,
    JournalTarget,
)
from src.state.models import (
    IntakeFormData,
    DataFile,
    DataExplorationResult,
    ColumnAnalysis,
    QualityIssue,
    VariableMapping,
    ResearchPlan,
    SearchQuery,
    SearchResult,
    AnalysisResult,
    Finding,
    Theme,
    LiteratureSynthesis,
    ResearchGap,
    GapAnalysis,
    ContributionStatement,
    RefinedResearchQuestion,
    DraftSection,
    ResearchDraft,
    CritiqueItem,
    Critique,
    EvidenceItem,
    WorkflowError,
    # Sprint 6 models
    StyleViolation,
    CitationEntry,
    ReferenceList,
    PaperSection,
    ArgumentThread,
    WriterOutput,
    SectionWritingContext,
    SECTION_WORD_COUNTS,
    get_section_word_count_target,
)
from src.state.schema import WorkflowState

__all__ = [
    # Enums
    "ResearchStatus",
    "CritiqueSeverity",
    "EvidenceStrength",
    "PaperType",
    "ResearchType",
    "GapType",
    "GapSignificance",
    # Sprint 6 enums
    "SectionType",
    "WritingStatus",
    "StyleViolationType",
    "CitationStyle",
    "JournalTarget",
    # Models
    "IntakeFormData",
    "DataFile",
    "DataExplorationResult",
    "ColumnAnalysis",
    "QualityIssue",
    "VariableMapping",
    "ResearchPlan",
    "SearchQuery",
    "SearchResult",
    "AnalysisResult",
    "Finding",
    "Theme",
    "LiteratureSynthesis",
    "ResearchGap",
    "GapAnalysis",
    "ContributionStatement",
    "RefinedResearchQuestion",
    "DraftSection",
    "ResearchDraft",
    "CritiqueItem",
    "Critique",
    "EvidenceItem",
    "WorkflowError",
    # Sprint 6 models
    "StyleViolation",
    "CitationEntry",
    "ReferenceList",
    "PaperSection",
    "ArgumentThread",
    "WriterOutput",
    "SectionWritingContext",
    "SECTION_WORD_COUNTS",
    "get_section_word_count_target",
    # Schema
    "WorkflowState",
]
